live_config_reload: true

mouse:
  hide_when_typing: true

hints:
  enabled:
    - regex: "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\" {-}\\^⟨⟩`]+"
      command: xdg-open
      post_processing: true
      mouse:
        enabled: true
        mods: Control

selection:
  semantic_escape_chars: "/-,│`|:\"' ()[]{}<>"
