#!/bin/sh

# script for calling at the startup
# increase key speed rate
xset r rate 300 50
# map caps lock to control
setxkbmap -option ctrl:nocaps
# when pressed once treat as escape
killall xcape 2>/dev/null; xcape -e 'Control_L=Escape'
# turn off caps lock
xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock
