#!/bin/sh
# commands used:
# - mpc

MUSIC_INFO=$(
  mpc status -f '[[%artist% / ]%title%]|[%file%]' 2> /dev/null
)

# only display something if the MPD is on
# and the songs queue is not empty
if [ -z "${MUSIC_INFO}" ] \
   || [ "$( mpc playlist | wc -l )" -eq 0 ]; then
  exit 0
fi

if echo "${MUSIC_INFO}" | grep -q '^\[playing\]'; then
  MUSIC_ICON=''
  MUSIC_TEXT=$(
    echo "${MUSIC_INFO}" \
      | head -n 1 \
      | cut -c -50
  )
elif echo "${MUSIC_INFO}" | grep -q '^\[paused\]'; then
  MUSIC_ICON=''
  MUSIC_TEXT='Paused'
else
  MUSIC_ICON=''
  MUSIC_TEXT='Stopped'
fi

TEXT="${MUSIC_ICON}  ${MUSIC_TEXT}"

pidof -x dwmblocks-mpdup >/dev/null 2>&1 || dwmblocks-mpdup >/dev/null 2>&1 &

printf '%s' "${TEXT}"
