alacritty: alacritty-configs
amfora: amfora-configs
coreutils: coreutils-configs
dwm: dwm-configs
dwmblocks: dwmblocks-configs dwmblocks-scripts
fontconfig: fontconfig-configs
git: git-configs git-docs git-scripts
gnupg: gnupg-configs
htop: htop-configs
httpie: httpie-configs
less: less-configs
dunst: dunst-configs
mpd: mpd-configs
nvim: nvim-configs
openssh: openssh-configs
qutebrowser: qutebrowser-configs
ripgrep: ripgrep-configs
newsboat: newsboat-configs
shell: shell-scripts shell-docs
slock: slock-configs
tmux: tmux-configs
translate-shell: translate-shell-configs
zathura: zathura-configs
zsh: zsh-configs
